const express = require("express");
const router = new express.Router();

const db = require("../db");
const ExpressError = require("../expressError");
const slugify = require("slugify"); // <-- ADDED

/** GET /companies => { companies: [{code, name}, ...] } */
router.get("/", async function (req, res, next) {
  try {
    const result = await db.query(
      `SELECT code, name
       FROM companies
       ORDER BY code`
    );
    return res.json({ companies: result.rows });
  } catch (err) {
    return next(err);
  }
});

/** GET /companies/:code
 *  => { company: { code, name, description, invoices:[id,...], industries:[name,...] } }
 */
router.get("/:code", async function (req, res, next) {
  try {
    const { code } = req.params;

    const compRes = await db.query(
      `SELECT code, name, description
       FROM companies
       WHERE code = $1`,
      [code]
    );
    if (compRes.rows.length === 0) {
      throw new ExpressError(`Company not found: ${code}`, 404);
    }

    const [invRes, indRes] = await Promise.all([
      db.query(
        `SELECT id
         FROM invoices
         WHERE comp_code = $1
         ORDER BY id`,
        [code]
      ),
      db.query(
        `SELECT i.industry
         FROM industries AS i
         JOIN companies_industries AS ci
           ON i.code = ci.ind_code
         WHERE ci.comp_code = $1
         ORDER BY i.industry`,
        [code]
      ),
    ]);

    const company = compRes.rows[0];
    company.invoices = invRes.rows.map(r => r.id);
    company.industries = indRes.rows.map(r => r.industry);

    return res.json({ company });
  } catch (err) {
    return next(err);
  }
});

/** POST /companies
 *  body: { name, description }
 *  => { company: { code, name, description } }
 *  Note: code is generated by slugify(name)
 */
router.post("/", async function (req, res, next) {              // modified this
  try {
    const { name, description } = req.body;
    if (!name) throw new ExpressError("name is required", 400);

    const code = slugify(name, { lower: true, strict: true }); // added this

    const result = await db.query(
      `INSERT INTO companies (code, name, description)
       VALUES ($1, $2, $3)
       RETURNING code, name, description`,
      [code, name, description || null]
    );

    return res.status(201).json({ company: result.rows[0] });
  } catch (err) {
    return next(err);
  }
});

/** PUT /companies/:code
 *  body: { name, description }
 */
router.put("/:code", async function (req, res, next) {
  try {
    const { code } = req.params;
    const { name, description } = req.body;

    const result = await db.query(
      `UPDATE companies
       SET name = $1,
           description = $2
       WHERE code = $3
       RETURNING code, name, description`,
      [name, description || null, code]
    );

    if (result.rows.length === 0) {
      throw new ExpressError(`Company not found: ${code}`, 404);
    }

    return res.json({ company: result.rows[0] });
  } catch (err) {
    return next(err);
  }
});

/** DELETE /companies/:code => { status: "deleted" } */
router.delete("/:code", async function (req, res, next) {
  try {
    const { code } = req.params;

    const result = await db.query(
      `DELETE FROM companies
       WHERE code = $1
       RETURNING code`,
      [code]
    );

    if (result.rows.length === 0) {
      throw new ExpressError(`Company not found: ${code}`, 404);
    }

    return res.json({ status: "deleted" });
  } catch (err) {
    return next(err);
  }
});

module.exports = router;
